<?php

return [

    'database' =>[
        'users'         => 'mysql_USERS',
        'lls_whip'      => 'mysql_LLS',
        'dts'           => 'mysql_DTS'
    ],
    
    'barangay' => [
        "Apil",
        "Binuangan",
        "Bolibol",
        "Buenavista",
        "Bunga",
        "Buntawan",
        "Burgos",
        "Canubay",
        "Clarin Settlement",
        "Dolipos Bajo",
        "Dolipos Alto",
        "Dulapo",
        "Dullan Norte",
        "Dullan Sur",
        "Lower Lamac",
        "Layawan",
        "Lower Langcangan",
        "Lower Loboc",
        "Lower Rizal",
        "Malindang",
        "Mialen",
        "Mobod",
        "Ciriaco Pastrano",
        "Paypayan",
        "Pines",
        "Poblacion 1",
        "Poblacion 2",
        "Proper Langcangan",
        "San Vicente Alto",
        "San Vicente Bajo",
        "Sebucal",
        "Senote",
        "Taboc Norte",
        "Taboc Sur",
        "Talairon",
        "Talic",
        "Toliyok",
        "Tipan",
        "Transville",
        "Tuyabang Alto",
        "Tuyabang Bajo",
        "Tuyabang Proper",
        "Upper Langcangan",
        "Upper Lamac",
        "Upper Loboc",
        "Upper Rizal",
        "Victoria",
        "Villaflor" 
    ],
];